config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :pictures
  resources :users, except: [:destroy]
  post 'users/new', to: 'users#create'
  get 'pictures/icon/:id', to: 'pictures#show'
  put 'pictures/icon/:id', to: 'pictures#icon', as: 'icon'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/picture.rb
class Picture < ApplicationRecord
  validates :title, presence: true, length: {minimum: 6, maximum: 100}
  validates :description, presence: true, length: {minimum: 10, maximum: 300}
  has_many :user_pictures
  has_many :users, through: :user_pictures
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_pictures
  has_many :pictures, through: :user_pictures
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, presence: true,
            uniqueness: { case_sensitive: false },
            length: {minimum: 3, maximum: 25}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
            uniqueness: { case_sensitive: false },
            length: { maximum: 105 },
            format: { with: VALID_EMAIL_REGEX }
end

app/models/user_picture.rb
class UserPicture < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  def after_sign_in_path_for(resource)
    if !current_user.admin?
      user_path(current_user)
    else
      users_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy, :icon]
  def show
  end
  def index
    if current_user.admin?
      @pictures = Picture.all
    else
      flash[:alert] = "Only admin can see all users"
      redirect_to current_user
    end
  end
  def new
    @picture = Picture.new
  end
  def edit
  end
  def create
    @picture = Picture.new(picture_params)
    @picture.users << current_user
    if @picture.save
      redirect_to @picture
      flash[:notice] = "Picture was created successfully."
    else
      render 'new'
    end
  end

  def update
    if @picture.update(picture_params)
      flash[:notice] = "Picture was updated successfully."
      redirect_to @picture
    else
      render 'edit'
    end
  end
  def destroy
    if !current_user.admin?
      @user = current_user
      @record = UserPicture.where(user_id: @user.id, picture_id: @picture.id).first
      # debugger(do: "info")
      @record.destroy
      redirect_to user_path
    else
      @picture.destroy
      redirect_to pictures_path
    end
  end
  def icon
    @user = current_user
    @pics = UserPicture.where(user_id: @user.id)
    @pics.each do |pic|
      pic.icon = false if pic.icon
      pic.save
    end
    @record = UserPicture.where(user_id: @user.id, picture_id: @picture.id).first
    @record.icon = true
    if @record.save
      flash[:notice] = "Icon was set successfully."
    end
    redirect_to user_path
  end

  private
  def set_picture
    @picture = Picture.find(params[:id])
  end
  def picture_params
    params.require(:picture).permit(:title, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end
  def index
    if current_user.admin?
      @users = User.all
    else
      flash[:alert] = "Only admin can see all users"
      redirect_to current_user
    end
  end

  def show
    @user = User.find(params[:id])
    @pics = UserPicture.where(user_id: @user.id)
    if !(current_user.admin? || @user == current_user)
      flash[:alert] = "Only admin can see other users"
      redirect_to current_user
    end
  end

  def edit
    @user = User.find(params[:id])
    if !(current_user.admin? || @user == current_user)
      flash[:alert] = "Only admin can edit other users"
      redirect_to current_user
    end
  end

  def update
    @user = User.find(params[:id])
    @count = 2
    @num = pic_params.dig(:picture_ids, 1)
    while @num != nil
      @num = pic_params.dig(:picture_ids, @count)
      @count += 1
    end
    if @count <= 5
      if @user.update(pic_params)
        flash[:notice] = "Picture collection was updated successfully."
        redirect_to @user
      else
        render 'edit'
      end
    else
      flash[:alert] = "You can choose only 3 pictures"
      render 'edit'
    end
  end

  def create
    debugger
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "#{@user.username} was successfully sign up"
      redirect_to users_path
    else
      render "new"
    end
  end

  private
  def pic_params
    params.require(:user).permit(picture_ids: [])
  end

  def user_params
    params.permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Copyright &copy; <%= link_to "Kseniya", "#", class: "text-white" %></small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container" id="page-content">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
        <%= msg %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%= link_to "PICTURES LIBRARY", root_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <% if current_user %>
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <% if current_user.admin? %>
            <li class="nav-item">
              <%= link_to "Users", users_path, class: "nav-link" %>
            </li>
          <% end %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Pictures
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Create new picture", new_picture_path, class: "dropdown-item"%></li>
              <% if current_user.admin? %>
                <li><%= link_to "View my pictures", user_path(current_user), class: "dropdown-item"%>
                <li><%= link_to "View all pictures", pictures_path, class: "dropdown-item"%></li>
              <% else %>
                <li><%= link_to "View my pictures", user_path(current_user), class: "dropdown-item"%>
              <% end %>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= "(Admin)" if current_user.admin? %> Profile [<%= current_user.username %>]
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "View your profile",  user_path(current_user), class: "dropdown-item" %></li>
              <li><%= link_to "Edit Account", edit_user_registration_path(current_user), class: "dropdown-item" %></li>
            </ul>
          </li>
        </ul>
      <% end %>
      <ul class="navbar-nav">
        <% if current_user %>
          <li class="nav-item"> <%= button_to "Log Out", destroy_user_session_path, method: :delete, class: "btn btn-small btn-primary mx-2" %></li>
        <% else %>
          <li class="nav-item"> <%= link_to "Sign Up", new_user_registration_path, class: "nav-link"  %></li>
          <li class="nav-item"> <%= link_to "Log In", new_user_session_path, class: "nav-link"  %></li>
        <% end %>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pictures</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1> This is the About Page</h1>

<%= link_to 'Articles listing', pictures_path %>
<%= link_to 'Home page', root_path %>

app/views/pages/home.html.erb
<div class="container mt-4" id="home-container">
  <div class="jumbotron text-center shadow p-3 mb-3 rounded">
    <h1 class="display-4">Pictures library</h1>
    <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
    <hr class="my-4">
    <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
    <%= link_to 'Log in', new_user_session_path, class: "btn btn-success btn-lg" %>
  </div>
</div>

app/views/pictures/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @picture %>
      <%= form_with(model: @picture, class: "shadow p-3 mb-3 bg-info rounded", local: true, data: {turbo: false})  do |f| %>
        <div class="form-group row">
          <%= f.label :title, class: "col-2 col-form-label text-light"%>
          <div class="col-10">
            <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of picture"%>
          </div>
        </div>

        <div class="form-group row mt-4">
          <%= f.label :description, class: "col-2 col-form-label text-light"%>
          <div class="col-10">
            <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of picture"%>
          </div>
        </div>

        <div class="row mt-4 justify-content-center">
          <div class="col-2">
            <%= f.submit class: "btn btn-outline-light btn-log" %>
          </div>
        </div>
      <% end %>
    </div>
    <%=link_to '[ Cancel and return to your page ]', user_path(current_user), class: "text-center text-info mb-3"%>
    </div>
</div>

app/views/pictures/edit.html.erb
<h1 class="text-center mt-4">Edit picture</h1>
<%= render 'form' %>

app/views/pictures/index.html.erb
<h1 class="text-center mt-4">Listing all pictures</h1>

<div class="container">
  <% @pictures.each do |picture| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="shadow mb-5 bg-body rounded">
          <div class="card text-center">
            <% if picture.users.any? %>
              <div class="card-header fst-italic">
                Used by:
                <div class="mt-2"><%= render picture.users %></div>
              </div>
            <% end %>
            <div class="card-body">
              <h5 class="card-title"><%= link_to picture.title, picture_path(picture), class: "text-success"%></h5>
              <p class="card-text"><%= truncate(picture.description, length: 100) %></p>
              <button class="btn btn-outline-success"><%= link_to 'Show', picture, class: "text-reset text-decoration-none" %></button>
              <% if user_signed_in? && (current_user.admin? || (picture.users.include? current_user)) %>
                <button class="btn btn-outline-primary"><%= link_to 'Edit', edit_picture_path(picture),  class: "text-reset text-decoration-none" %></button>
                <button class="btn btn-outline-danger"><%= link_to 'Delete', picture, data: { turbo_method: :delete, turbo_confirm: "Are you sure?"},  class: "text-reset text-decoration-none" %></button>
              <% end %>
            </div>
            <div class="card-footer text-muted">
              <small>Created <%= time_ago_in_words(picture.created_at) %> ago,
                edited <%= time_ago_in_words(picture.updated_at) %> ago</small>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <div class="mt-4 text-center">
    <%= link_to "Back", :back %>
  </div>
  <%#=link_to ' Cancel ', user_path(current_user), class: "text-center text-info mb-3"%>
</div>

app/views/pictures/new.html.erb
<h1 class="text-center mt-4">Create a new picture</h1>
<%= render 'form' %>

app/views/pictures/show.html.erb
<h2 class="text-center mt-4"><%= @picture.title %></h2>

<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="shadow mb-5 bg-body rounded">
        <div class="card text-center">
          <% if @picture.users.any? %>
            <div class="card-header fst-italic">
              Used by:
              <div class="mt-2"><%= render @picture.users %></div>
            </div>
          <% end %>
          <div class="card-body">
            <div class="card-text"><%= simple_format(@picture.description) %></div>
            <% if user_signed_in? && (current_user.admin? || (@picture.users.include?(current_user))) %>
              <button class="btn btn-outline-primary"><%= link_to 'Edit', edit_picture_path(@picture),  class: "text-reset text-decoration-none" %></button>
              <button class="btn btn-outline-danger"><%= link_to 'Delete', @picture, data: { turbo_method: :delete, turbo_confirm: "Are you sure?"},  class: "text-reset text-decoration-none" %></button>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(@picture.created_at) %> ago,
              edited <%= time_ago_in_words(@picture.updated_at) %> ago</small>
          </div>
        </div>
      </div>
      <div class="mt-4 text-center">
        <%= link_to "Back", :back %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the picture from being saved</h4>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_user.html.erb
<%= link_to user.username, user_path(user), class: "badge rounded-pill bg-info text-decoration-none" %>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Add pictures to collection</h1>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= form_with(model: @user, class: "shadow p-3 mb-3 bg-info rounded", local: true, data: {turbo: false})  do |f| %>
        <div class="form-group row mt-4">
          <%= f.label :picture, class: "col-2 col-form-label text-light"%>
          <div class="col-10">
            <%= f.collection_select :picture_ids, Picture.order(:title), :id, :title,
                                   { prompt: "Make your selection from the list below (can be empty), max: 3"},
                                   { multiple: true, size: 10, class: "form-select shadow rounded"}%>
          </div>
        </div>

        <div class="row mt-4 justify-content-center">
          <div class="col-2">
            <%= f.submit class: "btn btn-outline-light btn-log" %>
          </div>
        </div>
      <% end %>
    </div>
    <%=link_to ' Cancel ', user_path(current_user), class: "text-center text-info mb-3"%>
  </div>
</div>

app/views/users/index.html.erb
<h1 class="text-center mt-4">Users</h1>

<div class="text-center mt-4">
  <%= link_to "Create new user", new_user_path, class: "btn btn-outline-info" %>
</div>

<div class="container">
  <% @users.each do |user| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="shadow mb-5 bg-body rounded">
          <div class="card text-center">
            <div class="card-header fst-italic">
              <%= link_to user.username, user%>
            </div>
            <div class="card-body">
              <p class="card-text"><%= pluralize(user.pictures.count, "picture") %></p>
              <button class="btn btn-outline-success"><%= link_to 'View profile', user, class: "text-reset text-decoration-none" %></button>
              <button class="btn btn-outline-primary"><%= link_to 'Edit profile', edit_user_registration_path(user),  class: "text-reset text-decoration-none" %></button>
            </div>
            <div class="card-footer text-muted">
              <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<h2 class="text-center mt-4">Sign up</h2>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @user %>
      <%#= render "devise/shared/error_messages", resource: resource %>
      <%= form_with(method: 'POST', url: "/users/new", class: "shadow p-3 mb-3 bg-info rounded", local: true, data: {turbo: false})  do |f| %>

        <div class="form-group row">
          <%= f.label :username, class: "col-2 col-form-label text-light"%>
          <div class="col-10">
            <%= f.text_field :username, autofocus: true, class: "form-control shadow rounded", placeholder: "Enter a username"%>
          </div>
        </div>

        <div class="form-group row mt-4">
          <%= f.label :email, class: "col-2 col-form-label text-light"%>
          <div class="col-10">
            <%= f.email_field :email, autofocus: true,  autocomplete: "email", class: "form-control shadow rounded"%>
          </div>
        </div>

        <div class="form-group row mt-4">
          <div class="col-2 col-form-label text-light">
            <%= f.label :password %>
            <% if @minimum_password_length %>
              <em>(<%= @minimum_password_length %> characters minimum)</em>
            <% end %><br />
          </div>
          <div class="col-10">
            <%= f.password_field :password, autocomplete: "new-password", class: "form-control shadow rounded"%>
          </div>
        </div>

        <div class="row mt-4 justify-content-center">
          <div class="col-2">
            <%= f.submit "Sign up" , class: "btn btn-outline-light btn-log" %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="mt-4 text-center">
      <%= link_to "Back", :back %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%= @user.username %> profile</h1>

<% if user_signed_in? && (@user == current_user || current_user.admin?) %>
  <div class="text-center mt-4">
    <%= link_to "Edit Account", edit_user_registration_path, class: "btn btn-outline-info" %>
  </div>
  <div class="text-center mt-4">
    <%= link_to "Add pictures to collection", edit_user_path, class: "btn btn-outline-info" %>
  </div>
<% end %>

<h3 class="text-center mt-4">Pictures</h3>

<div class="container">
  <% @user.pictures.each do |picture| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="shadow mb-5 bg-body rounded">
          <div class="card text-center">
            <% if picture.users.any? %>
              <div class="card-header fst-italic">
                Used by:
                <div class="mt-2"><%= render picture.users %></div>
              </div>
            <% end %>
            <div class="card-body">
              <h5 class="card-title"><%= link_to picture.title, picture_path(picture), class: "text-success"%></h5>
              <p class="card-text"><%= truncate(picture.description, length: 100) %></p>
              <button class="btn btn-outline-success"><%= link_to 'View', picture, class: "text-reset text-decoration-none" %></button>
              <% if user_signed_in? && (current_user.admin? || (picture.users.include? current_user)) %>
                <button class="btn btn-outline-primary"><%= link_to 'Edit', edit_picture_path(picture),  class: "text-reset text-decoration-none" %></button>
                <button class="btn btn-outline-danger"><%= link_to 'Delete', picture, data: { turbo_method: :delete, turbo_confirm: "Are you sure?"},  class: "text-reset text-decoration-none" %></button>
            <% end %>
            </div>
            <div class="card-footer text-muted">
              <% if !UserPicture.where(user_id: @user.id, picture_id: picture.id).first.icon %>
              <button class="btn btn-outline-warning"><%= link_to 'Make the picture as an icon', icon_path(picture), data: { turbo_method: :put }, class: "text-reset text-decoration-none" %></button><br/>
              <% end %>
              <small>Created <%= time_ago_in_words(picture.created_at) %> ago,
                edited <%= time_ago_in_words(picture.updated_at) %> ago</small>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <div class="mt-4 text-center">
    <%= link_to "Back", :back %>
  </div>
</div>